# Generated by Django 4.2.7 on 2023-11-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='ID_Number',
        ),
        migrations.AddField(
            model_name='farmer',
            name='date_left',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='date_registered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
