# Generated by Django 4.2.7 on 2023-11-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_farmer_address_remove_farmer_id_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer',
            new_name='Register',
        ),
    ]
