# Generated by Django 4.2.7 on 2023-11-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_loan_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_applied',
            new_name='applied',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date_to_pay',
        ),
    ]
