# Generated by Django 4.2.7 on 2023-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_applied_loan_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='email',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='address',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fname',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='phone_number',
            new_name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='percentage_interest',
        ),
    ]
