# Generated by Django 4.2.7 on 2023-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_created_loan_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_ID', models.IntegerField()),
                ('a_phone', models.IntegerField(blank=True, null=True)),
                ('a_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
