# Generated by Django 4.2.7 on 2023-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_applicant_delete_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='a_phone',
            field=models.IntegerField(default=0),
        ),
    ]
