# Generated by Django 4.2.7 on 2023-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_applicant_a_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='a_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='a_phone',
            field=models.CharField(max_length=20),
        ),
    ]
