# Generated by Django 4.2.7 on 2023-11-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_applicant_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Created',
        ),
    ]
