# Generated by Django 4.2.7 on 2023-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_applicant_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='a_email',
            new_name='Your_Contact',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_ID',
            new_name='Your_ID',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_phone',
            new_name='Your_Loan',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='a_name',
            new_name='Your_Name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Your_Email',
            field=models.EmailField(default='+254', max_length=100),
        ),
    ]
