# Generated by Django 4.2.7 on 2023-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_your_loan_applicant_your_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
