# Generated by Django 4.2.7 on 2023-11-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_applicant_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_Amount',
            new_name='Your_amount',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_Contact',
            new_name='Your_contact',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_Email',
            new_name='Your_email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_ID',
            new_name='Your_id',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_Name',
            new_name='Your_name',
        ),
    ]
