# Generated by Django 4.2.7 on 2023-11-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_your_amount_applicant_your_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Your_amount',
            new_name='amount',
        ),
    ]
